databases:
  - name: newrelic_rails7
    databaseName: mysite
    user: newrelic_rails7

services:
  - type: web
    name: newrelic_rails7
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true